export const ambassadorsData = [
  {
    id: 1,
    name: "Anna & Mandi Vakili",
    slug: "anna-mandi-vakili",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "ENTERTAINMENT & CELEBRITIES",
    description: "Fashion and lifestyle influencers bringing you the latest trends",
  },
  {
    id: 2,
    name: "Name Here",
    slug: "tech-ambassador",
    image: "/images/profile2bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "TECH",
    description: "Tech enthusiast sharing the coolest gadgets",
  },
  {
    id: 3,
    name: "Name Here",
    slug: "lifestyle-ambassador",
    image: "/images/profile3bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "POPULAR",
    category: "LIFESTYLE",
    description: "Lifestyle content creator with amazing picks",
  },
  {
    id: 4,
    name: "Ashley Powers",
    slug: "ashley-powers",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "BEAUTY",
    description: "New box opening coming soon",
  },
  {
    id: 5,
    name: "Name Here",
    slug: "female-lifestyle",
    image: "/images/profile2bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "LIFESTYLE",
    description: "Curating the best lifestyle products",
  },
  {
    id: 6,
    name: "Name Here",
    slug: "tech-guru",
    image: "/images/profile3bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "TECH",
    description: "Your go-to tech expert",
  },
  {
    id: 7,
    name: "Name Here",
    slug: "gaming-pro",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "GAMING",
    description: "Gaming enthusiast with epic finds",
  },
  {
    id: 8,
    name: "Big Narstie",
    slug: "big-narstie",
    image: "/images/profile2bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "ENTERTAINMENT & CELEBRITIES",
    description: "Bringing you the hottest entertainment picks",
  },
  {
    id: 9,
    name: "Name Here",
    slug: "sports-fan",
    image: "/images/profile3bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "SPORTS",
    description: "Sports enthusiast with winning picks",
  },
  {
    id: 10,
    name: "Name Here",
    slug: "beauty-guru",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "BEAUTY",
    description: "Beauty expert with stunning selections",
  },
  {
    id: 11,
    name: "Name Here",
    slug: "blonde-lifestyle",
    image: "/images/profile2bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "LIFESTYLE",
    description: "Lifestyle influencer with amazing taste",
  },
  {
    id: 12,
    name: "Name Here",
    slug: "polo-lifestyle",
    image: "/images/profile3bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "LIFESTYLE",
    description: "Sophisticated lifestyle curator",
  },
  {
    id: 13,
    name: "Name Here",
    slug: "travel-explorer",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "TRAVEL",
    description: "Travel enthusiast sharing adventure finds",
  },
  {
    id: 14,
    name: "Name Here",
    slug: "sports-cap",
    image: "/images/profile2bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "SPORTS",
    description: "Sports lover with winning selections",
  },
  {
    id: 15,
    name: "Name Here",
    slug: "beauty-white",
    image: "/images/profile3bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "BEAUTY",
    description: "Beauty specialist with premium picks",
  },
  {
    id: 16,
    name: "Name Here",
    slug: "beard-lifestyle",
    image: "/images/profile1bg.png",
    bannerImage: "/images/profile-banner.jpg",
    badge: "NEW",
    category: "LIFESTYLE",
    description: "Lifestyle expert with great taste",
  },
]

export const ambassadorBoxesData = [
  // Ashley Powers boxes
  {
    id: 1,
    title: "Powers Picks",
    slug: "ashley-powers-picks",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 2,
    title: "Box Name",
    slug: "ashley-powers-box-2",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 3,
    title: "Box Name",
    slug: "ashley-powers-box-3",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 4,
    title: "Box Name",
    slug: "ashley-powers-box-4",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 5,
    title: "Box Name",
    slug: "ashley-powers-box-5",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 6,
    title: "Box Name",
    slug: "ashley-powers-box-6",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 7,
    title: "Box Name",
    slug: "ashley-powers-box-7",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 8,
    title: "Box Name",
    slug: "ashley-powers-box-8",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  {
    id: 9,
    title: "Box Name",
    slug: "ashley-powers-box-9",
    ambassadorId: 4,
    price: "100",
    image: "/images/profile1bg.png",
  },
  // Add more boxes for other ambassadors as needed
]
