export const allBoxesData = [
  {
    id: 1,
    title: "Box Name",
    slug: "ashley-powers-tech-box",
    creator: "Ashley Powers",
    image: "/images/box1.png",
    isNew: true,
    creatorAvatar: "/images/profile1bg.png",
  },
  {
    id: 2,
    title: "Box Name",
    slug: "tech-guru-box-1",
    creator: "Name Here",
    image: "/images/box2.png",
    isNew: true,
    creatorAvatar: "/images/profile2bg.png",
  },
  {
    id: 3,
    title: "Box Name",
    slug: "lifestyle-box-1",
    creator: "Name Here",
    image: "/images/box3.png",
    isNew: true,
    creatorAvatar: "/images/profile3bg.png",
  },
  {
    id: 4,
    title: "Box Name",
    slug: "gaming-box-1",
    creator: "Name Here",
    image: "/images/box1.png",
    isNew: true,
    creatorAvatar: "/images/profile1bg.png",
  },
  {
    id: 5,
    title: "Box Name",
    slug: "beauty-box-1",
    creator: "Name Here",
    image: "/images/box2.png",
    isNew: true,
    creatorAvatar: "/images/profile2bg.png",
  },
  {
    id: 6,
    title: "Box Name",
    slug: "sports-box-1",
    creator: "Name Here",
    image: "/images/box3.png",
    isNew: true,
    creatorAvatar: "/images/profile3bg.png",
  },
  {
    id: 7,
    title: "Box Name",
    slug: "travel-box-1",
    creator: "Name Here",
    image: "/images/box1.png",
    isNew: true,
    creatorAvatar: "/images/profile1bg.png",
  },
  {
    id: 8,
    title: "Box Name",
    slug: "fitness-box-1",
    creator: "Name Here",
    image: "/images/box2.png",
    isNew: true,
    creatorAvatar: "/images/profile2bg.png",
  },
  {
    id: 9,
    title: "Box Name",
    slug: "food-box-1",
    creator: "Name Here",
    image: "/images/box3.png",
    isNew: true,
    creatorAvatar: "/images/profile3bg.png",
  },
  {
    id: 10,
    title: "Box Name",
    slug: "entertainment-box-1",
    creator: "Name Here",
    image: "/images/box1.png",
    isNew: true,
    creatorAvatar: "/images/profile1bg.png",
  },
  {
    id: 11,
    title: "Box Name",
    slug: "jewelry-box-1",
    creator: "Name Here",
    image: "/images/box2.png",
    isNew: true,
    creatorAvatar: "/images/profile2bg.png",
  },
  {
    id: 12,
    title: "Box Name",
    slug: "crypto-box-1",
    creator: "Name Here",
    image: "/images/box3.png",
    isNew: true,
    creatorAvatar: "/images/profile3bg.png",
  },
]
