export const latestBoxes = [
  {
    id: 1,
    title: "Labubu Exclusive",
    slug: "labubu-exclusive",
    creator: "Fanboxes",
    image: "/images/box1.png",
    isNew: true,
  },
  {
    id: 2,
    title: "Powers Picks",
    slug: "ashley-powers-picks",
    creator: "Ashley Powers",
    image: "/images/box2.png",
    isNew: true,
  },
  {
    id: 3,
    title: "Box Name",
    slug: "big-narstie-box",
    creator: "Big Narstie",
    image: "/images/box3.png",
    isNew: true,
  },
  {
    id: 4,
    title: "Luxe Exclusive",
    slug: "luxe-exclusive",
    creator: "Fanboxes",
    image: "/images/box1.png",
    isNew: false,
  },
  {
    id: 5,
    title: "The Ultimate Techy",
    slug: "ultimate-techy",
    creator: "Fanboxes",
    image: "/images/box2.png",
    isNew: false,
  },
  {
    id: 6,
    title: "Footy Box",
    slug: "footy-box",
    creator: "Big Narstie",
    image: "/images/box3.png",
    isNew: false,
  },
  {
    id: 7,
    title: "On The Tools",
    slug: "on-the-tools",
    creator: "Fanboxes",
    image: "/images/box1.png",
    isNew: true,
  },
  {
    id: 8,
    title: "Rolex Box",
    slug: "rolex-box",
    creator: "Fanboxes",
    image: "/images/box2.png",
    isNew: true,
  },
  {
    id: 9,
    title: "Hole-in-one Box",
    slug: "hole-in-one-box",
    creator: "Fanboxes",
    image: "/images/box3.png",
    isNew: true,
  },
]

export const newAmbassadors = [
  { id: 1, name: "Ashley Powers", slug: "ashley-powers", image: "/images/profile1bg.png", isNew: true },
  { id: 2, name: "Name Here", slug: "name-here-2", image: "/images/profile2bg.png", isNew: true },
  { id: 3, name: "Name Here", slug: "name-here-3", image: "/images/profile3bg.png", isNew: true },
]

export const categories = [
  "TECH",
  "GAMING",
  "BEAUTY",
  "LIFESTYLE",
  "FITNESS & HEALTH",
  "FOOD & BEVERAGE",
  "TRAVEL",
  "COLLECTORS / HOBBYISTS",
  "DIY / CRAFT",
  "FAMILY",
  "BOOKS & LITERATURE",
  "ENTERTAINMENT & CELEBRITIES",
  "JEWELLERY",
  "CARS & BIKES",
  "SPORTS",
  "ONLY FANS",
  "STOCKS & CRYPTO",
]

export const trendingBoxes = [
  {
    id: 1,
    title: "Labubu Exclusive",
    slug: "labubu-exclusive-trending",
    creator: "Fanboxes",
    image: "/images/box1.png",
    isNew: false,
  },
  {
    id: 2,
    title: "Box Name",
    slug: "anna-mandi-box",
    creator: "Anna & Mandi Vakili",
    image: "/images/box2.png",
    isNew: false,
    creatorAvatar: "/images/profile1bg.png",
  },
  {
    id: 3,
    title: "Box Name",
    slug: "big-narstie-trending-box",
    creator: "Big Narstie",
    image: "/images/box3.png",
    isNew: false,
    creatorAvatar: "/images/profile2bg.png",
  },
]

export const trendingAmbassadors = [
  { id: 1, name: "Ashley Powers", slug: "ashley-powers", image: "/images/profile1bg.png", isNew: false },
  { id: 2, name: "Name Here", slug: "name-here-2", image: "/images/profile2bg.png", isNew: false },
  { id: 3, name: "Name Here", slug: "name-here-3", image: "/images/profile3bg.png", isNew: false },
]
